# Generated by Django 3.2.5 on 2021-08-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
