# Generated by Django 3.2.5 on 2021-08-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbackend', '0002_photographer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='appointments',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photographer',
            name='availability',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='company_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='distance_cost',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='size_cost',
            field=models.TextField(),
        ),
    ]
