# Generated by Django 3.2.5 on 2021-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbackend', '0003_auto_20210803_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='id',
        ),
        migrations.AlterField(
            model_name='photographer',
            name='vendor_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
