# Generated by Django 3.2.5 on 2021-08-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbackend', '0004_auto_20210803_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='photographer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
